import { useEffect, useState } from 'react'
import { Alert, Brand, Icon } from './App'
import { api, errorText, fmtDate, post } from './api'
import type { Json } from './api'
const statusNames:Record<string,string>={pending:'未受付',requested:'未受付',accepted:'受付済み',completed:'対応完了'}
export default function Staff({auth,logout}:{auth:string,logout:()=>void}) {
  const [calls,setCalls]=useState<Json[]>([])
  const [error,setError]=useState('')
  const [busy,setBusy]=useState('')
  const [updated,setUpdated]=useState('')
  const [filter,setFilter]=useState('active')
  async function refresh(){const data=await api<Json[]>('/staff/calls',{},undefined,auth);setCalls(data);setUpdated(new Date().toLocaleTimeString('ja-JP'));setError('')}
  useEffect(()=>{let alive=true;const poll=()=>{if(alive)refresh().catch(error=>{if(alive)setError(errorText(error))})};poll();const timer=setInterval(poll,2000);return()=>{alive=false;clearInterval(timer)}},[auth])
  async function act(call:Json,action:string){setBusy(call.id);setError('');try{await api(`/staff/calls/${call.id}/${action}`,post(),undefined,auth);await refresh()}catch(error){setError(errorText(error))}finally{setBusy('')}}
  const active=calls.filter(call=>call.status!=='completed')
  const visible=filter==='active'?active:calls
  return <div className="management-shell"><header className="management-header"><Brand/><span>スタッフ接客</span><div className="management-header-links"><a href="/">お客様ページ ↗</a><a href="/admin">管理者</a><button className="button subtle" onClick={logout}>ログアウト</button></div></header><main className="management-main staff-main"><div className="management-title"><div><span className="eyebrow">STAFF DESK</span><h1>お客様のご相談を、つなぐ。</h1><p>AI 接客からの呼出を受付し、対応状況をお客様ページに届けます。</p></div><span className="polling-label"><span className="live-dot"/>2 秒ごとに更新{updated&&<small>最終取得 {updated}</small>}</span></div><div className="staff-stats"><div className="card"><span>対応をお待ちのお客様</span><strong>{active.filter(call=>call.status!=='accepted').length}<small>件</small></strong></div><div className="card"><span>受付済み・対応中</span><strong>{calls.filter(call=>call.status==='accepted').length}<small>件</small></strong></div><div className="card"><span>対応完了</span><strong>{calls.filter(call=>call.status==='completed').length}<small>件</small></strong></div></div><Alert message={error}/><div className="section-heading staff-list-heading"><h2>スタッフ呼出</h2><div className="staff-filters"><button className={filter==='active'?'active':''} onClick={()=>setFilter('active')}>未完了 {active.length}</button><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>すべて {calls.length}</button></div></div>{visible.length?<div className="staff-call-grid">{visible.map(call=><article className={`card staff-call ${call.status}`} key={call.id}><div className="section-heading"><span className={`badge ${call.status==='completed'?'published':call.status==='accepted'?'confirmed':'uploaded'}`}>{statusNames[call.status] || call.status}</span><span className="small-note"><Icon name="clock" size={12}/> {fmtDate(call.created_at)}</span></div><h2>{call.property_name || 'お客様からのご相談'}</h2><dl><div><dt>呼出理由</dt><dd>{call.reason}</dd></div><div><dt>最近のご質問</dt><dd>{call.last_customer_question || '文字でのご質問はまだありません。'}</dd></div></dl><div className="staff-call-id">接客 ID: {call.session_id}</div>{call.status==='completed'?<p className="completed-label"><Icon name="check" size={15}/>対応完了 · {fmtDate(call.completed_at)}</p>:<button className={`button ${call.status==='accepted'?'secondary':'primary'} wide`} disabled={!!busy} onClick={()=>act(call,call.status==='accepted'?'complete':'accept')}>{busy===call.id?'更新しています…':call.status==='accepted'?'対応完了':'受付'}<Icon name="check" size={17}/></button>}</article>)}</div>:<div className="card empty-state staff-empty"><span className="staff-empty-icon"><Icon name="people" size={35}/></span><h2>現在、未完了の呼出はありません</h2><p>お客様から呼出が届くと、この画面に表示されます。<br/>この画面はサーバーの実際の呼出記録を取得しています。</p></div>}</main></div>
}
