// Real installed Chrome + real isolated FastAPI/SDK. No AI transport mocking.
import { chromium, expect } from '../frontend/node_modules/@playwright/test/index.mjs'
import fs from 'node:fs/promises'
import path from 'node:path'
const root=path.resolve(import.meta.dirname,'..')
const env=Object.fromEntries((await fs.readFile(path.join(root,'.env'),'utf8')).split('\n').filter(l=>l&&!l.startsWith('#')).map(l=>{const i=l.indexOf('=');return[l.slice(0,i),l.slice(i+1)]}))
const url=process.env.BROWSER_TEST_URL || 'http://127.0.0.1:5174'
const out=path.join(root,'evidence/browser');await fs.mkdir(out,{recursive:true})
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true})
const context=await browser.newContext({viewport:{width:1440,height:1100},locale:'ja-JP'})
const errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)))
const admin=await context.newPage()
const customer=await context.newPage()
const staff=await context.newPage()
let result={browser:'installed Google Chrome (headless)',api:'real isolated FastAPI :8001',sdk:'actual SANZO package 1.8.0',ai:'BLOCKED missing key',voice:'NOT_VERIFIED',scenarios:[]}
try{
  const health=await (await context.request.get(url+'/api/health')).json()
  if(health.demo_mode!=='test')throw new Error('Refusing to mutate non-test server')
  await admin.goto(url+'/admin')
  await admin.getByLabel('パスワード').fill(env.ADMIN_PASSWORD)
  await admin.getByRole('button',{name:'ログイン',exact:true}).click()
  await expect(admin.getByRole('heading',{name:'資料から、信頼できるご案内へ。'})).toBeVisible()
  const names=[]
  for(const filename of ['物件概要_demo.pdf','設備仕様_demo.pdf','周辺環境_demo.pdf','住宅ローン_demo.xlsx']){
    const name=filename.replace('_demo.','_Chrome検証.')
    names.push(name)
    await admin.locator('input[type=file]').setInputFiles({name,mimeType:filename.endsWith('.pdf')?'application/pdf':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:await fs.readFile(path.join(root,'demo_documents',filename))})
    await expect(admin.locator('.document-detail h2')).toHaveText(name)
    await admin.getByRole('button',{name:'SDK 解析を実行'}).click()
    await expect(admin.locator('#review-json')).toBeVisible()
    const normalized=JSON.parse(await admin.locator('#review-json').inputValue())
    if(filename.startsWith('物件概要'))expect(normalized.property.price).toBe(76900000)
    if(filename.startsWith('住宅ローン'))expect(normalized.rates).toHaveLength(2)
    await admin.getByLabel('確認メモ').fill('TEST: Chrome UI acceptance of verified SANZO demo document. Production manual approval remains separate.')
    await admin.getByLabel('資料と確認データを照合し、対象物件・適用条件・出典を確認しました。').check()
    await admin.getByRole('button',{name:'管理者確認を保存'}).click()
    await expect(admin.locator('.document-detail .badge')).toHaveText('確認済み')
    await admin.getByRole('checkbox',{name:`${name} を公開対象に選択`,exact:true}).check()
  }
  await admin.getByRole('button',{name:'選択資料を公開'}).click()
  await expect(admin.locator('.alert.success').first()).toContainText('公開版')
  await admin.screenshot({path:path.join(out,'admin-desktop.png'),fullPage:true})
  result.scenarios.push('Chrome UI upload -> real SDK parse -> explicit test-admin review -> publication of four files: PASS')
  await customer.goto(url+'/')
  await expect(customer.locator('.property-summary')).toContainText('76,900,000')
  await expect(customer.getByRole('button',{name:'接客を開始',exact:false})).toBeDisabled()
  await customer.getByRole('button',{name:'文字で開始'}).click()
  await expect(customer.locator('.session-caption')).toContainText('文字で接客中')
  await customer.getByLabel('ご相談内容',{exact:true}).fill('駅から何分ですか？')
  await customer.getByRole('button',{name:'送信',exact:true}).click()
  await expect(customer.getByRole('alert')).toContainText('OpenAI API Key が未設定')
  result.scenarios.push('Missing key is visibly rejected; no fake AI or voice success: PASS')
  await customer.getByLabel('頭金（円）').fill('5000000')
  await customer.getByLabel('返済期間（年）').fill('35')
  await customer.getByLabel('参考金利・商品').selectOption({label:(await customer.getByLabel('参考金利・商品').locator('option').allTextContents()).find(t=>t.includes('フラット35'))})
  await customer.getByRole('button',{name:'月額概算を計算'}).click()
  await expect(customer.locator('.mortgage-result')).toContainText('3.94%')
  await expect(customer.locator('.mortgage-result')).toContainText('本結果は概算です')
  result.scenarios.push('Loan 5m down /35y /Flat35 >90% uses backend3.94% condition with real result: PASS')
  await customer.getByLabel('ご相談内容',{exact:true}).fill('年収500万円なら絶対ローン通りますか？')
  await customer.getByRole('button',{name:'送信',exact:true}).click()
  await expect(customer.locator('.conversation')).toContainText('システム案内')
  await expect(customer.locator('.conversation')).toContainText('確定的なご案内はできません')
  await expect(customer.locator('.staff-status')).toContainText('呼出を受け付けました')
  await staff.goto(url+'/staff')
  await staff.getByLabel('パスワード').fill(env.STAFF_PASSWORD)
  await staff.getByRole('button',{name:'ログイン',exact:true}).click()
  const card=staff.locator('.staff-call').filter({hasText:'年収500万円なら絶対ローン通りますか？'}).first()
  await expect(card).toBeVisible()
  await card.getByRole('button',{name:'受付',exact:true}).click()
  await expect(customer.locator('.staff-status')).toContainText('スタッフが確認しました',{timeout:10000})
  await staff.screenshot({path:path.join(out,'staff-desktop.png'),fullPage:true})
  await card.getByRole('button',{name:'対応完了',exact:true}).click()
  await expect(customer.locator('.staff-status')).toContainText('スタッフの対応が完了しました',{timeout:10000})
  result.scenarios.push('Policy rejects judgement -> persisted staff record -> separate staff Chrome tab accepts/completes -> customer polling updates: PASS')
  await customer.screenshot({path:path.join(out,'customer-desktop.png'),fullPage:true})
  await customer.setViewportSize({width:820,height:1180})
  await expect(customer.locator('body')).toBeVisible()
  expect(await customer.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await customer.screenshot({path:path.join(out,'customer-tablet.png'),fullPage:true})
  result.scenarios.push('820px tablet width has no horizontal overflow: PASS')
  await customer.getByRole('button',{name:'接客終了',exact:true}).click()
  await expect(customer.getByRole('button',{name:'文字で開始'})).toBeVisible()
  expect(errors).toEqual([])
  result.status='PASS';result.uncaught_page_errors=errors
}catch(e){result.status='FAIL';result.error=e.message;await customer.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});throw e}
finally{await fs.writeFile(path.join(out,'result.json'),JSON.stringify(result,null,2));await browser.close();console.log(JSON.stringify(result,null,2))}
